#define Dabble_ID		     0x00
#define GAMEPAD_ID 			 0x01
#define TERMINAL_ID			 0x02
#define CONTROLS_ID          0x05
#define EVIVEINTERFACES_ID   0x09
//#define INTERNET_ID	 		 0x29
#define PINMONITOR_ID        0x03
#define SENSORS_ID           0x04
#define CAMERA_ID            0x06
#define LEDCONTROL_ID        0x0A
#define COLORDETECTOR_ID     0x0B
#define DATALOGGER_ID		 0x0C	
#define SMS_ID				 		 0x0D
#define NOTIFICATION_ID				 0x0D
#define MUSIC_ID					 0x0E
#define ROBOTICARM_ID                0x0F
#define HOMEAUTOMATION_ID            0x10
#define INTERNET_ID	 		         0x11

